### ISSUE TITLE
Another MooseDocs Edit

### ISSUE THREAD

**Issue by crswong888** [idaholab/mastodon#323]
@cbolisetti  Okay I have something else I'd like to change with the website. The "Getting Started" portion of the MOOSE website is going to be changing, as per idaholab/moose#15300, and so simply adding all of its content with `${MOOSE_DIR}/modules/doc/content/getting_started/**` in `config.yml` will cause issues with MASTODON documentation. We should only include the MooseDown files that we need, which are the following:

```
    - moose:
        root_dir: ${MOOSE_DIR}/modules/doc/content
        content:
            - getting_started/installation/install_conda_moose.md
            - getting_started/installation/install_miniconda.md
            - getting_started/installation/uninstall_conda.md
            - getting_started/installation/wsl.md
```

It turns out, that simply including all content from MOOSE's "Getting Started" causes another issue that is unrelated to idaholab/moose#15300: The page (`getting_started/index.md`) gets [added to the MASTODON website](https://mooseframework.org/mastodon/getting_started/), and is accessible through the breadcrumbs navigation bar when on the `mastodon_conda` or `mastodon_windows10` page. This page is only intended for the main MOOSE website.

(refs #321)
